### ISSUE TITLE
Bash scripts fails on Windows but work on WSL

### ISSUE THREAD

**Issue by mrvonwyl** [evilmartians/lefthook#551]
### :wrench: Summary

It looks like that bash scripts cannot be run with lefthook in a Windows environment.
The same config and script work fin in WSL and also with a js script and node.
But on Windows, there is a bash error: `No such file or directory`.
This is possibly due to a character escape issue.

I actually do not know if this should even be possible, but due to the nature of the error I think it should be, since node runs, but has a wrong path to the script.

### Lefthook version

1.4.11

### Steps to reproduce

1. Checkout https://github.com/mrvonwyl/lefthook-playground
2. Run `npm i` (which should also install the git hooks)
3. Run `npx lefthook -v run prepare-commit-msg`

### Expected results

The console should print "hello from bash".

### Actual results

The console prints an error instead: 
RUNNING HOOK: prepare-commit-msg
`⠙ waiting: bash.sh/bin/bash: F:Devplaygroundlefthook.lefthookprepare-commit-msgbash.sh: No such file or directory`
-> note the missing folder delimiters (/ or \)

### Possible Solution

-

### Logs / Screenshots

```
PS F:\Dev\playground\lefthook> npx lefthook -v run prepare-commit-msg
[lefthook] cmd: [git rev-parse --show-toplevel]
[lefthook] err: <nil>
[lefthook] out: F:/Dev/playground/lefthook

[lefthook] cmd: [git rev-parse --git-path hooks]
[lefthook] err: <nil>
[lefthook] out: .git/hooks

[lefthook] cmd: [git rev-parse --git-path info]
[lefthook] err: <nil>
[lefthook] out: .git/info

[lefthook] cmd: [git rev-parse --git-dir]
[lefthook] err: <nil>
[lefthook] out: .git

Lefthook v1.4.11
RUNNING HOOK: prepare-commit-msg
/bin/bash: F:Devplaygroundlefthook.lefthookprepare-commit-msgbash.sh: No such file or directory

  EXECUTE > bash.sh

            127
  EXECUTE > node.js
hello from node?


SUMMARY: (done in 0.20 seconds)
✔️  node.js
🥊  bash.sh
```

**Comment by mrexox** [comment]
Thank you for this catch! I will take a look at this issue this week.

**Comment by mrexox** [comment]
BTW, could you remove the `runner` option from the config for `bash.sh`? It must call the script directly. Does the error persist then?

**Comment by mrvonwyl** [comment]
I changed the config like so (is this what you meant be removing the runner?): 
```
prepare-commit-msg:
  scripts:
    "bash.sh":
    "node.js":
      runner: node
```

This results in the following error:
```
EXECUTE > bash.sh

            \Users\mrvon\dev\lefthook-playground\.lefthook\prepare-commit-msg\bash.sh: %1 is not a valid Win32 application.
```
This is probably caused due to windows not containing bash!?

**Comment by avudnez** [comment]
I second this, having the same error where bash seems to be called with a windows-style path containing no slash (neither forward nor backward).
This is unfortunately a blocker for lefthook adoption.

**Comment by yzhe554** [comment]
Also wanted to run shell script on windows but it's blocked.

**Comment by ianzone** [comment]
Mark https://github.com/evilmartians/lefthook/issues/953

**Comment by mrexox** [comment]
Hey! I have released a fix with 1.11.5 which must wrap the commands with `sh -c` just like on *nix systems. Could you please check if it works for you? Does the fix really fixes the issue? I don't use Windows daily so I might not have covered some edge case. I'd be glad to get any feedback!

**Comment by mrvonwyl** [comment]
Hey. Thank you for the update!

At first glance it looks like it is working, when I execute the hook through the cli:
![Image](https://github.com/user-attachments/assets/656ce741-8f95-4c58-addb-c3b3397f4ec3)

When running the hook via VS Code on Windows, I still have an issue where node is not found. But I suspect that is a missing configuration in combination with Git for Windows and fnm.

The issue with bash scripts on Windows is resolved in my eyes.

Thanks again :)
